default_agent: agentcore_strands
agents:
  agentcore_strands:
    name: agentcore_strands
    entrypoint: main.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::870529038310:role/agentcore-agentcore_strands-role
      execution_role_auto_create: true
      account: '870529038310'
      region: us-west-2
      ecr_repository: 870529038310.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-agentcore_strands
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: agentcore_strands-v7xaiKFOkf
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:870529038310:runtime/agentcore_strands-v7xaiKFOkf
      agent_session_id: 4a6a04d2-49f1-47bc-92d6-94d5bfbb554f
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    authorizer_configuration: null
    oauth_configuration: null
